---
- name: Create internet monitor group
  group:
    name: "internet_monitor"
    state: present
  become: true

# First this and next steps from https://stackoverflow.com/a/60533790
- name: Check if config dir exists
  stat:
    path: "{{ config_dir }}"
  register: output_folder
  become: true

- name: Create output directory if not exists
  file:
    path: "{{ config_dir }}"
    state: directory
    owner: "{{ ansible_user_id }}"
    group: internet_monitor
    mode: 0775
  when:
    - output_folder.stat.exists == false
  become: true

# After trying 3 methods of checking for systemd-resolved, I'm giving up
# and treating this like an exception block. Try to disable it. Most likely,
# the only reason it will fail on a fresh install is that it's not there.
- name: Try to stop systemd-resolved.service
  ansible.builtin.shell: sudo systemctl stop systemd-resolved.service
  become: true   # Ensure that the highest permissions are used on the remote host
  ignore_errors: true

- name: Try to disable systemd-resolved
  ansible.builtin.shell: sudo systemctl disable systemd-resolved.service
  become: true   # Ensure that the highest permissions are used on the remote host
  ignore_errors: true
